# Generated by Django 3.1.4 on 2023-05-21 16:23

import autoslug.fields
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210514_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='title', unique=True, verbose_name='url')),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=2000)),
                ('characteristics', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Characteristics')),
                ('image', models.ImageField(default='default1.jpg', upload_to='')),
                ('category', models.ManyToManyField(related_name='item_2', to='shop.Category')),
            ],
        ),
    ]
