# Generated by Django 3.1.4 on 2023-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='gsgF', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item2',
            name='category',
            field=models.ManyToManyField(related_name='item2', to='shop.Category'),
        ),
    ]
